version: "3.8"

services:
  frontend:
    container_name: portfolio_frontend
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    container_name: portfolio_backend
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
